# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84ffaf83bba43377b0174ab3c63e74f64f9bde41093ed01f9d3fde4c6df51e0c616b806efe25ad5b2d75b77ab0104f84dd96aec8ba3b8d744040d28091ff12a7

test:
  secret_key_base: 9a13dd31702b2e8d55337b6047743ae91d10e7b61b6ebb421d9a1dd7270a1e7a989a80f9c394547bbc0481681893161e01bcd52f2a0bad80764db3362518a995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
